server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: ns-framework-demo-app
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000

demo:
  travel:
    default-traveler-id: "1"
    default-travel-date-offset-days: 30
    services:
      hotel:
        url: http://localhost:8082
      flight:
        url: http://localhost:8084
      tourism:
        url: http://localhost:8085
    planner:
      docker-image: "aibasel/downward"
      container-command: "fast-downward.py --plan-file /planner/plan.txt /planner/domain.pddl /planner/problem.pddl --search 'astar(lmcut())'"
      plan-written-to-file: true
      timeout-seconds: 120
