server.port=8082
spring.application.name=mock-hotel-booking-service

# Swagger UI: http://localhost:8082/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.tesis.mock.booking.DebugHttpPayloadLoggingFilter=DEBUG
