server.port=8085
spring.application.name=mock-tourist-attractions-service

# Swagger UI: http://localhost:8085/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.tesis.mock.tourism.TouristAttractionsServiceApplication=DEBUG
