server.port=8084
spring.application.name=mock-flight-booking-service

# Swagger UI: http://localhost:8084/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.tesis.mock.flight.FlightBookingServiceApplication=DEBUG
